name: "Auto Update COUNTRIBUTING.md"

on:
  push:
    tags:
      - "v*" # 當推送以 v 開頭的標籤（如 v1.0.0）時觸發
      - "[0-9]*.[0-9]*.[0-9]" # 當推送符合版本號格式的標籤（如 1.0.0）時觸發
    # 允許手動觸發
  workflow_dispatch:

jobs:
  update-file:
    runs-on: ubuntu-latest
    permissions:
      contents: write # 需要寫入權限才能推送 Commit

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Update COUNTRIBUTING.md
        run: |
          npx credit-roll > ./docs/CREDITS.md

      - name: 提交並推送變更
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '📄 docs: Auto update CREDITS.md by Action'
